const mongoose=require('mongoose');

const referralSchema=new mongoose.Schema({
    referrer:{
        type:mongoose.Types.ObjectId,
        ref:'User',
        required:true
    },
    referee:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    referralMethod:{
        type:String,
        enum:['code','link'],
        required:true
    },
    referralCode:{
        type:String,
        uppercase:true
    },
    status:{
        type:String,
        enum:['pending','completed','failed'],
        default:'pending'
    },
    rewardDetails:{
        amount:{
            type:Number,
            required:true
        },
        rewardType:{
            type:String,
            default:'wallet-credit'
        },
        couponCode:String,
        discountValue:Number,
        creditedAt:Date
    },
    createdAt:{
        type:Date,
        default:Date.now
    },
    completedAt:{
        type:Date
    }
});
 const Referral=mongoose.model('Referral',referralSchema);
 module.exports=Referral;
